name = input("Enter your first name and last name: ").title()
print(name)
admision_number = int(input("Enter your student number: "))
# fruit = input()
# price = float(input())
# quality = int(input())
# for i in range(2):
fruit, price, quality = input(f"Enter your fruit name, unit price and quality: ").split(' ,', 3)
price = int(price)
quality = float(quality)
total = int(price) * float(quality)
# my_input1 = input(f"Enter your fruit name, unit price and quality {fruit}  {price} {quality}")
fruit1, price1, quality1 = input(f"Enter your fruit name, unit price and quality: ").split(',', 3)
price1 = int(price1)
quality1 = float(quality1)
total1 = int(price1) * float(quality1)

first_name = input("Enter first name: ")
second_name = input("Enter last name: ")
# second_name.upper()
admission = int(input("Student Number: "))
print("---------------------------------------------------")
print("Item       UnitPrice        Quantity         Total")
print("===================================================")

print(f"{fruit}  \t\t {price}   \t\t\t  {quality}   \t\t   {total}")
print(f"{fruit1}  \t {price1}   \t\t\t   {quality1}   \t\t   {total1}")
